### ISSUE TITLE
error when make tesseract

### ISSUE THREAD

**Issue by vanchung1995** [tesseract-ocr/tesstrain#182]
I'm trying ` make leptonica tesseract` but it raise error. I'm using ubuntu 18.04 and installed packages at https://tesseract-ocr.github.io/tessdoc/Compiling

the error same this link: https://stackoverflow.com/questions/57952135/makefile213-recipe-for-target-tesseract-built-failed-make-tesseract-buil
this is screenshot of error

![Screenshot from 2020-08-05 15-40-50](https://user-images.githubusercontent.com/15941200/89391224-1c382680-d732-11ea-93e9-4e583dc8ab18.png)

**Comment by kba** [comment]
Best to ask on [the tesseract mailing list](https://groups.google.com/forum/#!forum/tesseract-ocr)

**Comment by stweil** [comment]
Please don't use screenshots of textual error messages. Adding the text or uploading the log file is better because it can be indexed by search engines.

Your build fails because `pdfrenderer.cpp` was not compiled. The matching error message is missing in your screenshot. Always look for the first error when there is a problem.
