### ISSUE TITLE
What is the procedure from messy images to annotated data

### ISSUE THREAD

**Issue by datavistics** [tesseract-ocr/tesstrain#98]
I apologize in advance if this is listed somewhere, I cant seem to find these answers. 

I have messy images containing text that are scanned in mostly arabic and some english. The english is minimal like `(N123.23, W231.43)` for example. 
I want to use tesstrain to finetune existing models. 

1. When creating the bounding boxes and adding the text, can this be done on a line by line basis or do I need to draw bounding boxes around individual characters?
2. Are there guidelines on how tight these bounding boxes need to be?
3. How does the ordering work for arabic characters?
ال باب
Is the first character ا or ب?
4. How do I handle English and Arabic in the same document? Its very minimal english, only a couple characters like above.

Currently Im annotating these using the [VGG VIA V2 Image tool](http://www.robots.ox.ac.uk/~vgg/software/via/). And can convert the output as necessary. If you know of a better way, please let me know.

**Comment by wrznr** [comment]
Mixed LTR and RTL will be tough if it is possible at all. You can definitely work on a line-by-line basis. That's one big advantage of LSTM-based OCR. The bounding boxes should be as tight as necessary in order to exclude characters from other lines while including all characters from the line under consideration. We have good experiences with https://www.primaresearch.org/tools/Aletheia

**Comment by wrznr** [comment]
It might be an option to train two models. One for the Arabic part and one for the Latin characters. Tesseract can make use of both at runtime!
